version: 2
jobs:
    test:
        docker:
            - image: circleci/python:3.7.3
        steps:
            - checkout
            - run:
                name: Install dependencies.
                command: pip install -r requirements.txt
            - run:
                name: Lint code.
                command: pylint UnleashClient -f parseable >> pylint.log
            - run:
                name: Run mypy
                command: mypy UnleashClient >> mypy.log
            - run:
                name: Run unit tests.
                command: py.test --junitxml=pytest/results.xml --cov=UnleashClient tests/unit_tests
            - store_test_results:
                path: pytest
            - store_artifacts:
                path: pylint.log
            - store_artifacts:
                path: mypy.log
            - run:
                name: Send code coverage to Coveralls
                command: pipenv run coveralls
    toxify:
        docker:
             - image: themattrix/tox
        steps:
            - checkout
            - run: 
                name: "Run tox"
                command: tox

workflows:
    version: 2
    build_and_test:
        jobs:
            - test
            - toxify