version: 2
jobs:
    test:
        docker:
            - image: circleci/python:3.7.3
        steps:
            - checkout
            - run:
                name: Install dependencies.
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
            - run:
                name: Lint code.
                command: |
                    . venv/bin/activate
                    mypy UnleashClient >> mypy.log
                    pylint UnleashClient -f parseable >> pylint.log
            - run:
                name: Run unit tests.
                command: |
                    . venv/bin/activate
                    py.test --html=pytest/results.html --junitxml=pytest/results.xml --self-contained-html --cov=UnleashClient tests/unit_tests
            - run:
                name: Run specification tests.
                command: |
                    . venv/bin/activate
                    py.test tests/specification_tests
            - store_test_results:
                path: pytest
            - store_artifacts:
                path: pylint.log
            - store_artifacts:
                path: mypy.log
            - run:
                name: Send code coverage to Coveralls
                command: |
                    . venv/bin/activate
                    coveralls
    toxify:
        docker:
             - image: themattrix/tox
        steps:
            - checkout
            - run: 
                name: "Run tox"
                command: tox

workflows:
    version: 2
    build_and_test:
        jobs:
            - test
            - toxify