name: UCP - CI pipeline

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Linting
        run: |
          mypy UnleashClient
          pylint UnleashClient
      - name: Unit tests
        run: |
          py.test --html=pytest/results.html --junitxml=pytest/results.xml --self-contained-html --cov=UnleashClient tests/unit_tests
      - name: Specification tests
        run: |
          py.test tests/specification_tests
      - name: Send coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.coveralls_repo_token }}
        run: |
          coveralls